version: '3'
services:
  app:
    image: node:14-alpine
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules:
